version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: crud_db
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend-net
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    networks:
      - backend-net

  backend:
    build: ./backend
    container_name: backend-app
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - backend-net
  
  frontend:
    build: ./frontend
    container_name: frontend-app
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - backend-net


networks:
  backend-net:

volumes:
  db_data:
